import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import { passportApi as api } from '../api/passport'
import styles from '../styles/Passport.module.css'
import AccountIcon from '../components/Common/AccountIcon'
import TicketQrDialog from '../components/Common/TicketQrDialog'

const text = {
    ua: { title: 'Особистий кабінет', tagline: 'Твої квитки, бонусні бали та налаштування.', profile: 'Мій профіль', profileSettings: 'Налаштування профілю', tabs: ['Огляд', 'Квитки', 'Бали за контент', 'Історія балів', 'Налаштування'], login: 'Увійти', email: 'Email, який використовував для покупки', request: 'Отримати код', code: 'Код із листа', verify: 'Підтвердити', change: 'Змінити email', generic: 'Якщо цей email має покупки, код надійде на пошту. Перевір також спам.', available: 'Доступні бали', reserved: 'У резерві', tickets: 'Мої квитки', buy: 'Обрати подію', share: 'Поділись своїм рейвом', shareText: 'Надішли посилання на публікацію або Reel в Instagram. Команда перевірить контент і нарахує бали.', url: 'Посилання на Instagram', note: 'Коментар (необов’язково)', submit: 'На перевірку', submitted: 'Посилання надіслано на перевірку.', empty: 'Тут поки немає записів.', qr: 'Показати QR-код', qrError: 'Не вдалося завантажити QR-код. Спробуй ще раз.', historyHelp: 'Тут відображаються нарахування за покупки й контент, списання на знижки та коригування балів.', hide: 'Закрити', subscribe: 'Хочу отримувати анонси electroperedachi на email. Можу відписатися в будь-який момент.', logout: 'Вийти', loading: 'Завантаження…', retry: 'Спробувати ще раз', pending: 'На перевірці', approved: 'Схвалено', rejected: 'Відхилено', paid: 'Ціна квитка', scanned: 'Використано', next: 'Далі', prev: 'Назад', recover: 'Немає доступу до старої пошти? Звернися до команди для перевірки покупки.', free: 'Безкоштовні квитки не дають балів.', disabled: 'Програма балів ще не активована.', saved: 'Збережено', rate: 'Курс бала', reward: 'Бали за покупку', limit: 'Максимальна знижка', purchase: 'Покупка квитків', content: 'Контент схвалено', redemption: 'Оплата балами', adjustment: 'Коригування', refund: 'Повернення' },
    en: { title: 'My account', tagline: 'Your tickets, reward points and preferences.', profile: 'My profile', profileSettings: 'Profile settings', tabs: ['Overview', 'Tickets', 'Content rewards', 'Points history', 'Settings'], login: 'Sign in', email: 'Email used to buy tickets', request: 'Get a code', code: 'Code from your email', verify: 'Verify', change: 'Change email', generic: 'If this email has purchases, a code will arrive shortly. Check your spam folder too.', available: 'Available points', reserved: 'Reserved', tickets: 'My tickets', buy: 'Choose an event', share: 'Share your rave', shareText: 'Send a link to your Instagram post or Reel. Our team reviews it and awards points.', url: 'Instagram link', note: 'Note (optional)', submit: 'Submit for review', submitted: 'Link submitted for review.', empty: 'No records yet.', qr: 'Show QR code', qrError: 'Could not load the QR code. Please try again.', historyHelp: 'Purchase and content rewards, points spent on discounts and balance adjustments appear here.', hide: 'Close', subscribe: 'Email me electroperedachi announcements. I can unsubscribe at any time.', logout: 'Sign out', loading: 'Loading…', retry: 'Try again', pending: 'Pending review', approved: 'Approved', rejected: 'Rejected', paid: 'Ticket price', scanned: 'Used', next: 'Next', prev: 'Previous', recover: 'Lost access to your old email? Contact the team to verify your purchase.', free: 'Free tickets do not earn points.', disabled: 'The points programme is not active yet.', saved: 'Saved', rate: 'Point value', reward: 'Purchase reward', limit: 'Maximum discount', purchase: 'Ticket purchase', content: 'Content approved', redemption: 'Paid with points', adjustment: 'Adjustment', refund: 'Refund' }
}
export default function Account() {
    const { locale } = useRouter(), t = text[locale] || text.ua
    const [account, setAccount] = useState(null), [tab, setTab] = useState(0), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true)
    const [error, setError] = useState(''), [notice, setNotice] = useState(''), [email, setEmail] = useState(''), [code, setCode] = useState(''), [sent, setSent] = useState(false)
    const [tickets, setTickets] = useState([]), [history, setHistory] = useState([]), [submissions, setSubmissions] = useState([]), [page, setPage] = useState(1), [total, setTotal] = useState(0)
    const [url, setUrl] = useState(''), [note, setNote] = useState(''), [qr, setQr] = useState(null)
    async function refresh() {
        setLoading(true); setError('')
        try { setAccount(await api.me()) } catch (e) { if (e.response?.status !== 401) setError(e.response?.data?.message || 'Connection error'); setAccount(null) } finally { setLoading(false) }
    }
    useEffect(() => { refresh() }, [])
    useEffect(() => {
        if (!account) return
        let active = true
        setLoading(true); setError(''); setNotice('')
        const promise = tab === 1 ? api.tickets(page) : tab === 2 ? api.submissions() : tab === 3 ? api.history(page) : Promise.resolve(null)
        promise.then(r => { if (!active || !r) return; if (tab === 1) { setTickets(r.tickets); setTotal(r.total) } if (tab === 2) setSubmissions(r.submissions); if (tab === 3) { setHistory(r.entries); setTotal(r.total) } }).catch(e => { if (!active) return; if (e.response?.status === 401) setAccount(null); setError(e.response?.data?.message || 'Connection error') }).finally(() => { if (active) setLoading(false) })
        return () => { active = false }
    }, [account, tab, page])
    async function run(fn) { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await fn() } catch (e) { setError(e.response?.data?.message || 'Connection error') } finally { setBusy(false) } }
    const date = value => value ? new Date(value).toLocaleDateString(locale === 'en' ? 'en-GB' : 'uk-UA') : ''
    return <div className={styles.main}><Head><title>{`${t.title} | electroperedachi`}</title><meta name="robots" content="noindex,nofollow" /></Head>
        <div className={styles.eyebrow}>electroperedachi</div><h1>{t.title}</h1><p>{t.tagline}</p>
        {error && <div className={styles.notice} role="alert">{error} <button onClick={refresh}>{t.retry}</button></div>}{notice && <div className={styles.notice} role="status">{notice}</div>}
        {!account ? <section className={styles.login}><h2>{t.login}</h2><form onSubmit={e => { e.preventDefault(); run(async () => { if (sent) { await api.verifyCode(email, code); setCode(''); await refresh() } else { await api.requestCode(email); setSent(true); setNotice(t.generic) } }) }}>
            <label htmlFor="passport-email">{t.email}</label><input id="passport-email" type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} required disabled={sent || busy} />
            {sent && <><label htmlFor="passport-code">{t.code}</label><input id="passport-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e => setCode(e.target.value)} required /></>}
            <button className={styles.primary} disabled={busy || loading}>{busy ? t.loading : sent ? t.verify : t.request}</button>{sent && <button type="button" onClick={() => { setSent(false); setCode(''); setNotice('') }}>{t.change}</button>}
        </form><p>{t.recover} <Link href="/contacts">electroperedachi</Link></p></section> : <>
        <nav className={styles.tabs} aria-label={t.title}>{t.tabs.map((label, i) => <button key={label} aria-pressed={tab === i} onClick={() => { setTab(i); setPage(1); setQr(null) }}>{label}</button>)}</nav>
        {loading && <p role="status">{t.loading}</p>}
        {tab === 0 && <><div className={styles.grid}><section className={`${styles.card} ${styles.profile}`}><div className={styles.profileIcon}><AccountIcon size={32} /></div><h2>{account.user.name || t.profile}</h2><p className={styles.email}>{account.user.email}</p>{account.user.phone && <p>{account.user.phone}</p>}<button type="button" onClick={() => { setTab(4); setPage(1) }}>{t.profileSettings}</button></section><section className={styles.card}><h2>{t.available}</h2><div className={styles.balance}>{account.wallet.available}</div><p>{t.reserved}: {account.wallet.reserved}</p><p>{t.rate}: {(account.rules.pointValueKopecks / 100).toFixed(2)} ₴<br />{t.reward}: {account.rules.purchasePercent}%<br />{t.limit}: {account.rules.maxRedemptionPercent}%</p><p>{t.free}</p>{!account.rules.enabled && <p>{t.disabled}</p>}<Link className={styles.primary} href="/events">{t.buy}</Link></section></div><section className={`${styles.card} ${styles.section}`}><h2>{t.share}</h2><p>{t.shareText}</p><button onClick={() => setTab(2)}>{t.submit}</button></section></>}
        {tab === 1 && <section className={styles.card}><h2>{t.tickets}</h2>{!tickets.length && !loading && <p>{t.empty}</p>}{tickets.map(ticket => <div className={styles.row} key={ticket._id}><div><h3>{ticket.eventId?.title || 'electroperedachi'}</h3><p>{ticket.ticketTypeId?.name} · {date(ticket.createdAt)} · {t.paid}: {ticket.price ?? '—'} ₴ {ticket.isChecked && `· ${t.scanned}`}</p></div><button disabled={busy || ticket.voidedAt} onClick={() => setQr(ticket)}>{t.qr}</button></div>)}{qr && <TicketQrDialog ticket={qr} text={t} onClose={() => setQr(null)} />}</section>}
        {tab === 2 && <div className={styles.grid}><section className={styles.card}><h2>{t.share}</h2><p>{t.shareText}</p><form onSubmit={e => { e.preventDefault(); run(async () => { await api.submit(url, note); setSubmissions((await api.submissions()).submissions); setUrl(''); setNote(''); setNotice(t.submitted) }) }}><label htmlFor="instagram-url">{t.url}</label><input id="instagram-url" type="url" required value={url} onChange={e => setUrl(e.target.value)} placeholder="https://www.instagram.com/reel/…" /><label htmlFor="instagram-note">{t.note}</label><textarea id="instagram-note" maxLength={500} value={note} onChange={e => setNote(e.target.value)} /><button className={styles.primary} disabled={busy}>{t.submit}</button></form></section><section className={styles.card}>{!submissions.length && !loading && <p>{t.empty}</p>}{submissions.map(s => <div className={styles.row} key={s._id}><div><a href={s.url} target="_blank" rel="noopener noreferrer">Instagram</a><p>{date(s.createdAt)} · {t[s.status]}{s.status === 'approved' && ` · +${s.points}`}</p>{s.reason && <p>{s.reason}</p>}</div></div>)}</section></div>}
        {tab === 3 && <section className={styles.card}><h2>{t.tabs[3]}</h2><p>{t.historyHelp}</p>{!history.length && !loading && <p>{t.empty}</p>}{history.map(entry => <div className={styles.row} key={entry._id}><div><b>{t[entry.kind] || entry.kind}</b><p>{date(entry.sourceDate || entry.createdAt)}{entry.kind === 'adjustment' && ` · ${entry.reason}`}</p></div><strong>{entry.points > 0 ? '+' : ''}{entry.points}</strong></div>)}</section>}
        {tab === 4 && <section className={styles.card}><h2>{account.user.email}</h2><p>{account.user.phone}</p><label className={styles.checkbox}><input type="checkbox" checked={!!account.user.marketingConsent} disabled={busy} onChange={e => { const value = e.target.checked; run(async () => { await api.preferences(value); setAccount({ ...account, user: { ...account.user, marketingConsent: value } }); setNotice(t.saved) }) }} />{t.subscribe}</label><button onClick={() => run(async () => { await api.logout(); setAccount(null); setSent(false); setCode('') })}>{t.logout}</button></section>}
        {[1, 3].includes(tab) && <div className={styles.pagination}><button disabled={page === 1 || loading} onClick={() => setPage(page - 1)}>{t.prev}</button><span>{page}</span><button disabled={page * (tab === 1 ? 20 : 30) >= total || loading} onClick={() => setPage(page + 1)}>{t.next}</button></div>}
        </>}
    </div>
}
